openapi: 3.0.0
paths:
  /auth/login:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TelegramInitDataDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenDto"
        "400":
          description: ""
      tags:
        - Authorization
  /asset:
    get:
      operationId: AssetController_getPlayerAssets
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerAssetsDto"
      tags:
        - Asset
      security:
        - bearer: []
  /asset/charge-points:
    post:
      operationId: AssetController_chargePoints
      parameters: []
      responses:
        "201":
          description: ""
        "400":
          description: Not enough energy
      tags:
        - Asset
      security:
        - bearer: []
  /asset/time-to-full-energy:
    get:
      operationId: AssetController_getTimeToFullEnergy
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RemainingTimeDto"
      tags:
        - Asset
      security:
        - bearer: []
  /referral:
    get:
      operationId: ReferralController_getReferrals
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: perPage
          required: true
          in: query
          schema:
            type: number
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginatedResponse"
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/ReferralDto"
      tags:
        - Referral
      security:
        - bearer: []
  /event/tap:
    patch:
      operationId: EventController_tap
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TapEventDto"
      responses:
        "200":
          description: ""
      tags:
        - Event
      security:
        - bearer: []
info:
  title: Ambeaver API
  description: ""
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    TelegramInitDataDto:
      type: object
      properties:
        initData:
          type: string
      required:
        - initData
    AccessTokenDto:
      type: object
      properties:
        access_token:
          type: string
      required:
        - access_token
    PlayerAssetsDto:
      type: object
      properties:
        points:
          type: number
        energy:
          type: number
        ar:
          type: number
      required:
        - points
        - energy
        - ar
    RemainingTimeDto:
      type: object
      properties:
        remainingTime:
          type: number
      required:
        - remainingTime
    PaginationMeta:
      type: object
      properties:
        page:
          type: number
        perPage:
          type: number
        totalPages:
          type: number
        totalItems:
          type: number
      required:
        - page
        - perPage
        - totalPages
        - totalItems
    PaginatedResponse:
      type: object
      properties:
        meta:
          $ref: "#/components/schemas/PaginationMeta"
      required:
        - meta
    ReferralDto:
      type: object
      properties:
        username:
          type: string
        ar:
          type: number
      required:
        - ar
    TapEventDto:
      type: object
      properties:
        amount:
          type: number
          minimum: 1
      required:
        - amount
