openapi: 3.0.0
paths:
  /auth/login:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TelegramInitDataDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenDto"
        "400":
          description: ""
      tags:
        - Authorization
  /asset:
    get:
      operationId: AssetController_getPlayerAssets
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerAssetsDto"
      tags:
        - Asset
      security:
        - bearer: []
  /event/tap:
    patch:
      operationId: EventController_tap
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TapEventDto"
      responses:
        "200":
          description: ""
      tags:
        - Event
      security:
        - bearer: []
info:
  title: Ambeaver API
  description: ""
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    TelegramInitDataDto:
      type: object
      properties:
        initData:
          type: string
      required:
        - initData
    AccessTokenDto:
      type: object
      properties:
        access_token:
          type: string
      required:
        - access_token
    PlayerAssetsDto:
      type: object
      properties:
        points:
          type: number
        energy:
          type: number
        ar:
          type: number
      required:
        - points
        - energy
        - ar
    TapEventDto:
      type: object
      properties:
        amount:
          type: number
          minimum: 1
      required:
        - amount
